package com.eli.calc.shape.service.ws;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-27T23:26:14.041-04:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://ws.service.shape.calc.eli.com/", name = "ShapeCalculatorWebService")
//@XmlSeeAlso({com.eli.calc.shape.model.ObjectFactory.class, com.eli.calc.shape.service.ws.parms.ObjectFactory.class, com.eli.calc.shape.service.ws.resp.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-09-27T23:26:14.041-04:00", comments = "Apache CXF 3.1.7")
public interface ShapeCalculatorWebService {

    @WebMethod
    @WebResult(name = "RunPendingRequestsResponse", targetNamespace = "http://resp.ws.service.shape.calc.eli.com/", partName = "response")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-09-27T23:26:14.041-04:00")
    public com.eli.calc.shape.service.ws.resp.RunPendingRequestsResponse runAllPendingRequestsNoStopOnError();

    @WebMethod
    @WebResult(name = "QueueResponse", targetNamespace = "http://resp.ws.service.shape.calc.eli.com/", partName = "response")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2016-09-27T23:26:14.041-04:00")
    public com.eli.calc.shape.service.ws.resp.StatusResponse queueCalculation(
        @WebParam(partName = "parameters", name = "QueueRequestParms", targetNamespace = "http://parms.ws.service.shape.calc.eli.com/")
        com.eli.calc.shape.service.ws.parms.QueueRequestParms parameters
    );
}
